CREATE TABLE OpenTextTask (
    id BIGINT(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_OpenTextTask_Task FOREIGN KEY (id) REFERENCES Task(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;