CREATE TABLE MultipleChoiceTask (
    id BIGINT NOT NULL,
    CONSTRAINT FK_MultipleChoiceTask_Task FOREIGN KEY (id) REFERENCES Task(id) ON DELETE CASCADE,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
